### ISSUE TITLE
2 Customized widgets 

### ISSUE THREAD

**Issue by iifast1** [abhibagul/MagZ-Gaming-Free-Blogger-Template#2]
issue #1  not solved yet !

**Comment by abhibagul** [comment]
I have fixed the issue with the template few hours back. Download the template again and reupload it. Please do not open resolved issues. #1.

**Comment by iifast1** [comment]
but this is after your last update (#1 ) still having the same issue, some other people might be dealing with the same thing who used it before . these screenshots are after your last update today.
